version: "3.1"
services:
  db:
    image: postgres
    container_name: postgresqldb
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=MovieDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    volumes:
      - C:\docker_file\postgres_data://var/lib/postgresql/data

  app:
    build: .
    container_name: movieApp
#    image: movieapp
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/MovieDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update